[[redirects]]
  from = "https://steve.dellavalentina.com/*"
  to = "https://stevedv.com/:splat"
  status = 307
  force = true
  
[[redirects]]
  from = "https://sdv.im/*"
  to = "https://stevedv.com/:splat"
  status = 307
  force = true
  
[[redirects]]
  from = "https://blog.stevedv.com/*"
  to = "https://stevedv.com/blog/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "origin-when-cross-origin"